(define-library (libs tests mutable-vector-test)
  (export run-tests)
  (import (scheme base)
          (scheme write)
          (srfi 64)
          (libs mutable-vector))
  (begin
    (define (run-tests)
      (test-begin "make-mutable-vector-tests")
      (let ((mv (make-mutable-vector))
            (mv-preallocated (make-mutable-vector 10)))
        (test-assert (mutable-vector? mv))
        (test-assert (mutable-vector? mv-preallocated))
        (test-equal 0 (mutable-vector-length mv))
        (test-equal 0 (mutable-vector-length mv-preallocated)))
      (test-end "make-mutable-vector-tests"))))
