;; A centralized place to create a function that will load all of the files in the
;; system that comprise my SICP work so I can work in an iterative fashion
(define (load-func)
  (load "/home/jgonis/code/sicp/seasonedSchemer/seasonedSchemerCh11.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/seasonedSchemerCh12.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/seasonedSchemerCh13.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/seasonedSchemerCh14.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/seasonedSchemerCh16.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/seasonedSchemerCh18.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/seasonedSchemerCh19.sld")
    (load "/home/jgonis/code/sicp/seasonedSchemer/seasonedSchemerCh20.sld")
  ;; Test Files
  (load "/home/jgonis/code/sicp/seasonedSchemer/testsCh11.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/testsCh12.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/testsCh13.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/testsCh14.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/testsCh16.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/testsCh18.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/testsCh19.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/testsCh20.sld")
  (load "/home/jgonis/code/sicp/seasonedSchemer/tests.sld"))
