(define (load-func)
  (load "/Users/jeffgonis/code/sicp/concabs/libs/fungraph.sld")
  (load "/Users/jeffgonis/code/sicp/concabs/libs/fungraph-svg.sld")
  (load "/Users/jeffgonis/code/sicp/concabs/libs/quilting.sld")
  (load "/Users/jeffgonis/code/sicp/concabs/helpers.scm")
  (load "/Users/jeffgonis/code/sicp/concabs/ch2.scm")
  (load "/Users/jeffgonis/code/sicp/concabs/ch2Tests.scm"))
