(define (load-func)
  (load "/Users/jeffgonis/code/sicp/concabs/libs/fungraph-svg.sld")
  (load "/Users/jeffgonis/code/sicp/concabs/libs/quilting.sld")
  (load "/Users/jeffgonis/code/sicp/concabs/libs/digits.sld")
  (load "/Users/jeffgonis/code/sicp/concabs/libs/helpers.sld")
  (load "/Users/jeffgonis/code/sicp/concabs/ch2.scm")
  (load "/Users/jeffgonis/code/sicp/concabs/ch2Tests.scm"))
