(define (load-func)
  (load "/home/jgonis/Code/sicp/concabs/libs/fungraph.sld")
  (load "/home/jgonis/Code/sicp/concabs/libs/fungraph-svg.sld")
  (load "/home/jgonis/Code/sicp/concabs/libs/quilting.sld")
  (load "/home/jgonis/Code/sicp/concabs/libs/digits.sld")
  (load "/home/jgonis/Code/sicp/concabs/helpers.scm")
  (load "/home/jgonis/Code/sicp/concabs/ch2.scm")
  (load "/home/jgonis/Code/sicp/concabs/ch2Tests.scm"))
